const path = require("path")
require('dotenv').config({ path: path.join(__dirname, '.env') })

module.exports = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  HOST: process.env.HOST || 'localhost',
  PORT: process.env.PORT || 3000,
  APP_DOMAIN: process.env.APP_DOMAIN || 'localhost',
  APP_NAME: process.env.APP_NAME || 'Gorda',
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID || 'gorda-driver',
  FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL || 'http://localhost:9000',
  AUTHENTICATION_EMULATOR_HOST: process.env.AUTHENTICATION_EMULATOR_HOST || 'http://localhost:9099',
  DATABASE_EMULATOR_HOST: process.env.DATABASE_EMULATOR_HOST || 'localhost',
  DATABASE_EMULATOR_PORT: process.env.DATABASE_EMULATOR_PORT || 9000,
  FIRESTORE_EMULATOR_HOST: process.env.FIRESTORE_EMULATOR_HOST || 'localhost:8080',
  STORAGE_EMULATOR_HOST: process.env.STORAGE_EMULATOR_HOST || 'http://localhost:9199',
  DEFAULT_CLIENT_PHOTO_URL: process.env.DEFAULT_CLIENT_PHOTO_URL || 'http://localhost',
  PQR_NUMBER: process.env.PQR_NUMBER || '+573000000000',
  SENTRY_DSN: process.env.SENTRY_DSN || 'https://12f48cf123d54e30ace09a12359f4b48@o13012345.ingest.sentry.io/123456',
  CHROMIUM_PATH: process.env.CHROMIUM_PATH || '/usr/bin/chromium-browser',
  CANCEL_TIMEOUT: process.env.CANCEL_TIMEOUT || 480000,
  DISCONNECT_TIMEOUT: process.env.DISCONNECT_TIMEOUT || 900000,
  ABANDONED_SESSIONS_TIMEOUT: process.env.ABANDONED_SESSIONS_TIMEOUT || 1800000,
  GORDA_API_FUNCTIONS: process.env.GORDA_API_FUNCTIONS || 'http://127.0.0.1:5001/gorda-driver/us-central1/api',
  ENTITY_MODEL_NAME: process.env.ENTITY_MODEL_NAME || undefined,
  HUGGINGFACE_TOKEN: process.env.HUGGINGFACE_TOKEN || 'api-token',
  MESSAGE_TIMEOUT: process.env.MESSAGE_TIMEOUT || 5000,
  ARCHIVE_CHAT_TIMEOUT: process.env.ARCHIVE_CHAT_TIMEOUT || 2000,
  WWEB_VERSION: process.env.WWEB_VERSION || '2.2412.54',
  WAPI_TOKEN: process.env.WAPI_TOKEN || '',
  WAPI_URL: process.env.WAPI_URL || 'https://graph.facebook.com/v20.0/',
  GOOGLE_APPLICATION_CREDENTIALS: process.env.GOOGLE_APPLICATION_CREDENTIALS || '/root/wp-api/firebaseAccount.json',
  REDIS_HOST: process.env.REDIS_HOST || 'localhost',
  REDIS_PORT: process.env.REDIS_PORT || 6379,
  DATABASE_URL: process.env.DATABASE_URL || 'postgres://user:password@localhost:5432/gorda',
}