export enum WpEvents {
    AUTHENTICATED = 'authenticated',
    AUTHENTICATION_FAILURE = 'auth_failure',
    READY = 'ready',
    MESSAGE_RECEIVED = 'message',
    MESSAGE_CREATE = 'message_create',
    MESSAGE_REVOKED_EVERYONE = 'message_revoke_everyone',
    MESSAGE_REVOKED_ME = 'message_revoke_me',
    MESSAGE_ACK = 'message_ack',
    MESSAGE_EDIT = 'message_edit',
    MEDIA_UPLOADED = 'media_uploaded',
    CONTACT_CHANGED = 'contact_changed',
    GROUP_JOIN = 'group_join',
    GROUP_LEAVE = 'group_leave',
    GROUP_ADMIN_CHANGED = 'group_admin_changed',
    GROUP_MEMBERSHIP_REQUEST = 'group_membership_request',
    GROUP_UPDATE = 'group_update',
    QR_RECEIVED = 'qr',
    LOADING_SCREEN = 'loading_screen',
    DISCONNECTED = 'disconnected',
    STATE_CHANGED = 'change_state',
    BATTERY_CHANGED = 'change_battery',
    REMOTE_SESSION_SAVED = 'remote_session_saved',
    CALL = 'call'
}